# Generated by Django 5.1.6 on 2025-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="crop_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
