# Generated by Django 5.1.6 on 2025-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0002_alter_farmer_crop_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentmodel",
            name="profit_generated",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
