# Generated by Django 5.1.6 on 2025-02-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0004_alter_investmentmodel_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='requiredamount',
            field=models.BigIntegerField(default=0),
        ),
    ]
