# Generated by Django 5.1.6 on 2025-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0005_investmentmodel_requiredamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="farm_type",
            field=models.CharField(default="normal", max_length=255, null=True),
        ),
    ]
