# Generated by Django 5.1.6 on 2025-04-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0006_farmer_farm_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="crop_type",
            field=models.CharField(default="null", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="farm_type",
            field=models.CharField(default="farmer", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="soil_type",
            field=models.CharField(default="null", max_length=255, null=True),
        ),
    ]
