# Generated by Django 5.1.6 on 2025-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "businessmodel",
            "0007_alter_farmer_crop_type_alter_farmer_farm_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="crop_type",
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="soil_type",
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
