# Generated by Django 5.1.6 on 2025-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0008_alter_farmer_crop_type_alter_farmer_soil_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="land_area",
            field=models.BigIntegerField(null=True),
        ),
    ]
