# Generated by Django 5.1.6 on 2025-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0009_alter_farmer_land_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="land_area",
            field=models.BigIntegerField(default=0),
        ),
    ]
