# Generated by Django 5.1.6 on 2025-04-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0010_alter_farmer_land_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="token",
            field=models.BigIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="investmentmodel",
            name="is_verified",
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name="verifymodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crpimg", models.ImageField(upload_to="product_images/")),
                ("iasimg", models.ImageField(upload_to="product_images/")),
                ("doc_number", models.BigIntegerField()),
                ("articleimg", models.ImageField(upload_to="product_images/")),
                ("artlink", models.CharField(max_length=255)),
                ("is_approved", models.BooleanField(null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="businessmodel.farmer",
                    ),
                ),
                (
                    "investment_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="businessmodel.investmentmodel",
                    ),
                ),
            ],
        ),
    ]
