# Generated by Django 5.1.6 on 2025-04-03 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessmodel", "0011_farmer_token_investmentmodel_is_verified_verifymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_queries",
                        to="businessmodel.farmer",
                    ),
                ),
                (
                    "investment_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_queries",
                        to="businessmodel.investmentmodel",
                    ),
                ),
                (
                    "verifymodel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="businessmodel.verifymodel",
                    ),
                ),
            ],
        ),
    ]
