# Generated by Django 5.1.6 on 2025-02-16 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_dob_customuser_phno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dob",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phno",
            field=models.CharField(default="000000000"),
        ),
    ]
