# Generated by Django 5.1.6 on 2025-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_alter_customuser_phno_alter_customuser_profile_pic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="wallet_pin",
            field=models.IntegerField(null=True),
        ),
    ]
