# Generated by Django 5.1.6 on 2025-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_wallet_wallet_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_pin",
            field=models.CharField(null=True),
        ),
    ]
