# Generated by Django 5.1.6 on 2025-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_managers_customuser_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_vfc",
            field=models.BooleanField(default=False),
        ),
    ]
