# Generated by Django 5.1.6 on 2025-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.URLField(default='https://default-profile-pic-url.jpg')),
                ('post_image', models.URLField()),
                ('caption', models.TextField(blank=True)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
    ]
