# Generated by Django 5.1.6 on 2025-02-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetails',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='location',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='postdetails',
            name='username',
        ),
    ]
