# Generated by Django 5.1.6 on 2025-02-17 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_postdetails_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetails',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postdetails',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postdetails',
            name='post_image',
            field=models.ImageField(default=1, upload_to='post_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetails',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='profile_pics/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetails',
            name='username',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
