# Generated by Django 5.1.6 on 2025-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_image_alter_post_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
