# Generated by Django 5.1.6 on 2025-02-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='postdetails',
        ),
    ]
