# Generated by Django 5.1.6 on 2025-02-21 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0004_alter_investmentmodel_estimated_time'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supportpost',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='supportpost',
            name='requested_support_amount',
        ),
        migrations.RemoveField(
            model_name='supportpost',
            name='requesting_user',
        ),
        migrations.RemoveField(
            model_name='supportpost',
            name='sponsoring_user',
        ),
        migrations.RemoveField(
            model_name='supportpost',
            name='support_image',
        ),
        migrations.AddField(
            model_name='supportpost',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportpost',
            name='investmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='support_posts', to='businessmodel.investmentmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportpost',
            name='requiredamount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='support_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
