# Generated by Django 5.1.6 on 2025-02-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_supportpost_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportpost',
            name='requiredamount',
        ),
    ]
