# Generated by Django 5.1.6 on 2025-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
    ]
