# Generated by Django 5.1.6 on 2025-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(default="eatables"),
        ),
    ]
